=== hsinyinfu/XML_HW/bookDB.dtd
<?xml version="1.0" encoding ="UTF-8" ?>
<!--bookDB.dtd: Database containing books -->

<!ELEMENT bookDB ( book+ )>

<!ENTITY	TP		"Terence Parr">
<!ENTITY	YDL	"Y. Daniel Liang">
<!ENTITY	AA		"Andrew Appel">

<!ENTITY % CH "( chapter, description )">

<!ELEMENT book ( author+, image*, content+, newchapters* )>
<!ATTLIST book bookID ID #REQUIRED>
<!ELEMENT author ( #PCDATA )>
<!ELEMENT image ( #PCDATA )>

<!ELEMENT content %CH; >
<!ELEMENT newchapters %CH; >
<!ATTLIST newchapters added ( true | false ) "false">

<!ELEMENT chapter ( #PCDATA )>
<!ATTLIST chapter number CDATA #REQUIRED>

<!ELEMENT description ( section*, resources*, summary? )>

<!ELEMENT section ( #PCDATA )>

<!ELEMENT resources ( #PCDATA )>

<!ELEMENT summary ( #PCDATA )>

=== hsinyinfu/XML_HW/bookDB.xml
<?xml version = "1.0" ?>
<!DOCTYPE bookDB SYSTEM "bookDB.dtd" >

<bookDB>
<book bookID = "ID01">
	<author>&TP;</author>
	<content>
		<chapter number = "1"> hello </chapter>
		<description></description>
	</content>
</book>

<book bookID = "ID02">
	<author>&YDL;</author>
	<image>image of Python程式設計入門指南</image>
	<content>
		 <chapter number="1">電腦、程式及Python概述</chapter>
		 <description>
			<section>a</section>
		 </description>
	 </content>
	 <newchapters added="true">
		<chapter number = "2">hi</chapter>
		<description>
			<section>1</section>
			<resources>abc</resources>
		</description>
	 </newchapters>
</book>

<book bookID = "ID03">
	<author>&AA;</author>
	<image>image of Compiling with Continuations</image>
	<content>
		 <chapter number=""></chapter>
		 <description>
			<section>123</section>
			<resources>lsdkfj</resources>
			<summary>good</summary>
		 </description>
	 </content>
	 <newchapters added="false">
	 	<chapter number = "3"></chapter>
		<description></description>
	 </newchapters>
 </book>
 </bookDB>
